from pathlib import Path

ROOT = Path(__file__).resolve().parent
WEIGHTS_DIR = ROOT / "weights"
OUTPUT_DIR = ROOT / "output"
WEIGHTS_DIR.mkdir(exist_ok=True)
OUTPUT_DIR.mkdir(exist_ok=True)

PLAYER_DETECTION_WEIGHTS = WEIGHTS_DIR / "football-player-detection.pt"
BALL_DETECTION_WEIGHTS = WEIGHTS_DIR / "football-ball-detection.pt"
PITCH_DETECTION_WEIGHTS = WEIGHTS_DIR / "football-pitch-detection.pt"

CLASS_BALL = 0
CLASS_GOALKEEPER = 1
CLASS_PLAYER = 2
CLASS_REFEREE = 3

PLAYER_CONF = 0.30
BALL_CONF = 0.30
PITCH_CONF = 0.30
NMS_IOU = 0.50
INFERENCE_IMGSZ = 640

TRACKER_FRAME_RATE = 30
TRACKER_TRACK_BUFFER = 60
TRACKER_MATCH_THRESH = 0.85
TRACKER_HIGH_THRESH = 0.30
TRACKER_LOW_THRESH = 0.10

HOMOGRAPHY_MIN_INLIERS = 6
HOMOGRAPHY_SMOOTHING = 0.85
PITCH_DETECTION_EVERY_N_FRAMES = 15

PITCH_OUT_WIDTH_PX = 1050
PITCH_OUT_HEIGHT_PX = 680
PITCH_MARGIN_PX = 40
